name: Build FS25 Mod Helper EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd fs25-mod-helper-portable
          npm install

      - name: Build UI
        run: |
          cd fs25-mod-helper-portable
          npm run build

      - name: Build Windows EXE
        run: |
          cd fs25-mod-helper-portable
          npm run dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: fs25-mod-helper-exe
          path: fs25-mod-helper-portable/dist_electron/**
